Download list

diff --git a/misc/download-video b/misc/download-video
--- a/misc/download-video
+++ b/misc/download-video
@@ -13,9 +13,9 @@ __usage_page() {
     echo "Usage: $(basename $0) [<option>]*"
     echo "Option:"
     echo "    -y <URL>:          YouTube resource URL"
-    echo "    -r <resolution>:   Video resolution, currently"
-    echo "                         supported: sd, hd (default), full-hd"
+    echo "    -r <resolution>:   Video resolution, numeric"
     echo "    -c:                Attach cookies to request"
+    echo "    -l <location>:     File for a list of URLs"
     echo "    -p:                Pack MP4 files into a ZIP file and delete MP4 files"
     echo "    -m:                Move all ZIP files to 'DOWLOADS_HOME' location"
     echo "    -h:                Displays this help message"
@@ -117,31 +117,38 @@ _create_cookies() {
     esac
 }
 
-_get_resolution() {
-    local _resolution=${1:-}
+_select_resolution() {
+    echo "Which resolution do you want?" >&2
+    echo "1) SD (480p)" >&2
+    echo "2) HD (720p) (default)" >&2
+    echo "3) Full HD (1080p)" >&2
+    read -p "resolution-index> " _resolution_index
 
-    case "$_resolution" in
-        sd)
+    if [ -z "$_resolution_index" ]; then
+        _resolution_index=2
+    fi
+
+    case "$_resolution_index" in
+        1)
             echo "480"
             ;;
-        hd)
+        2)
             echo "720"
             ;;
-        full-hd)
+        3)
             echo "1080"
             ;;
-        *)
-            echo "720"
+        * )
+            echo "Invalid resolution option: $_resolution_index" >&2
+            _stopped
             ;;
     esac
 }
 
 _download_video() {
     local _url=${1:-}
-    local _resolution=$( _get_resolution ${2:-} )
-    local _cookies=$( _create_cookies ${3:-} )
-
-    cd "$YT_DLP_VIDEO_OUTPUT_FOLDER"
+    local _resolution=${2:-}
+    local _cookies=${3:-}
 
     if [ -f "$_cookies" ]; then
         yt-dlp -S "res:$_resolution" --recode-video "mp4" --cookies "$_cookies" --rm-cache-dir "$_url"
@@ -151,15 +158,39 @@ _download_video() {
 
     echo ;
     [ $? -eq 0 ] && echo "Downloaded: $_url" >&2 || echo "Unable to download: $_url" >&2
+}
+
+_download_resource() {
+    local _url=${1:-}
+    local _list=${2:-}
+    local _res=${3:-$( _select_resolution )}
+    local _cookies=${4:-}
+
+    cd "$YT_DLP_VIDEO_OUTPUT_FOLDER"
+
+    if [ -z "$_list" ]; then
+        _download_video "$_url" "$_res" "$_cookies"
+    else
+        while IFS= read -r line || [ -n "$line" ]; do
+            _download_video "$line" "$_res" "$_cookies"
+        done < $_list
+
+        echo ;
+        cat $_list
+        rm -f $_list
+    fi
 
     rm -f "$_cookies"
 }
 
+_src_url=""
+_list_file=""
 _cookies_flag=0
 _resolution=""
 _source=""
+_cookies_file=""
 
-while getopts "y:r:cpmh" opt; do
+while getopts "y:r:cl:pmh" opt; do
     case "$opt" in
         y)
             _src_url="$OPTARG"
@@ -170,6 +201,9 @@ while getopts "y:r:cpmh" opt; do
             ;;
         c)
             _cookies_flag=1
+            ;;
+        l)
+            _list_file="$OPTARG"
             ;;
         p)
             _pack_videos
@@ -183,10 +217,10 @@ while getopts "y:r:cpmh" opt; do
     esac
 done
 
-if [ $_cookies_flag -ne 1 ]; then
-    _source=""
+if [ $_cookies_flag -eq 1 ]; then
+    _cookies_file=$( _create_cookies "$_source" )
 fi
 
-_download_video "$_src_url" "$_resolution" "$_source"
+_download_resource "$_src_url" "$_list_file" "$_resolution" "$_cookies_file"
 
 _completed
