Container tag

diff --git a/llm/start-openwebui b/llm/start-openwebui
--- a/llm/start-openwebui
+++ b/llm/start-openwebui
@@ -4,8 +4,13 @@ BASEDIR=$(dirname $0); cd $BASEDIR
 . ../.libs/funcs
 . ../env-vars
 
+_require_var OPEN_WEBUI_PORT
 _require_var OPEN_WEBUI_WAIT_SECS
 _require_var OPEN_WEBUI_WAIT_TRIES
+
+# http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
+: "${OPEN_WEBUI_TAG:=auto}"
+: "${OPEN_WEBUI_OLLAMA_SERVER:=http://127.0.0.1:11434}"
 
 _usage() {
     echo "Starts Ollama service and the Open WebUI."
@@ -18,31 +23,68 @@ _usage() {
     exit 0
 }
 
-_remove_container() {
-    echo "Removing open-webui-cuda ..."
-    docker rm -f open-webui-cuda
+_remove_container_by_tag() {
+    local _tag=${1:-}
 
-    echo "Removing open-webui-main ..."
-    docker rm -f open-webui-main
+    if [ -n "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
+        echo "Removing open-webui-$_tag ..."
+        docker rm -f open-webui-$_tag
+    else
+        echo "Already removed open-webui-$_tag"
+    fi
+}
+
+_remove_container() {
+    if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
+        _remove_container_by_tag "cuda"
+        _remove_container_by_tag "main"
+    else
+        _remove_container_by_tag "$OPEN_WEBUI_TAG"
+    fi
     
     _completed
 }
 
-_stop_container() {
-    if [ -n "$(docker ps -q -a -f name=open-webui-cuda)" ]; then
-        echo "Stopping open-webui-cuda ..."
-        docker container stop open-webui-cuda
-    fi
+_stop_container_by_tag() {
+    local _tag=${1:-}
 
-    if [ -n "$(docker ps -q -a -f name=open-webui-main)" ]; then
-        echo "Stopping open-webui-main ..."
-        docker container stop open-webui-main
+    if [ -n "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
+        echo "Stopping open-webui-$_tag ..."
+        docker container stop open-webui-$_tag
+    else
+        echo "Already stopped open-webui-$_tag"
+    fi
+}
+
+_stop_container() {
+    if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
+        _stop_container_by_tag "cuda"
+        _stop_container_by_tag "main"
+    else
+        _stop_container_by_tag "$OPEN_WEBUI_TAG"
     fi
 
     _completed
 }
 
-_with_gpus=""
+_start_container_by_tag() {
+    local _tag=${1:-}
+    local _gpu_opt=${2:-}
+
+    if [ -z "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
+        echo ;
+        echo "Attempting to run open-webui-$_tag ..."
+
+        docker run -d --network=host -e PORT="$OPEN_WEBUI_PORT" -e OLLAMA_BASE_URL="$OPEN_WEBUI_OLLAMA_SERVER" $_gpu_opt -v open-webui:/app/backend/data --name open-webui-$_tag ghcr.io/open-webui/open-webui:$_tag
+
+        echo !!
+    else
+        echo ;
+        echo "Attempting to restart open-webui-$_tag ..."
+
+        docker container restart open-webui-$_tag
+    fi
+}
 
 while getopts "srh" opt; do
     case "$opt" in
@@ -64,37 +106,23 @@ fi
 
 _recognized_container=""
 
-if [ -z "$(docker ps -q -a -f name=open-webui-cuda)" ]; then
-    echo ;
-    echo "Attempting to run open-webui-cuda ..."
+if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
+    _start_container_by_tag "cuda" "--gpus all"
 
-    docker run -d --network=host -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --gpus all -v open-webui:/app/backend/data --name open-webui-cuda ghcr.io/open-webui/open-webui:cuda
-else
-    echo ;
-    echo "Attempting to restart open-webui-cuda ..."
-
-    docker container restart open-webui-cuda
-fi
-
-if ! [ $? -eq 0 ]; then
-    echo ;
-    echo "Unable to run open-webui-cuda"
-
-    if [ -z "$(docker ps -q -a -f name=open-webui-main)" ]; then
+    if ! [ $? -eq 0 ]; then
         echo ;
-        echo "Attempting to run open-webui-main ..."
+        echo "Unable to run open-webui-cuda"
 
-        docker run -d --network=host -e OLLAMA_BASE_URL=http://127.0.0.1:11434 -v open-webui:/app/backend/data --name open-webui-main ghcr.io/open-webui/open-webui:main
+        _start_container_by_tag "main"
+
+        _recognized_container=open-webui-main
     else
-        echo ;
-        echo "Attempting to restart open-webui-main ..."
-
-        docker container restart open-webui-main
+        _recognized_container=open-webui-cuda
     fi
-
-    _recognized_container=open-webui-main
 else
-    _recognized_container=open-webui-cuda
+    _start_container_by_tag "$OPEN_WEBUI_TAG" "$OPEN_WEBUI_GPU_OPT"
+
+    _recognized_container=open-webui-$OPEN_WEBUI_TAG
 fi
 
 _recognized_container_id="$(docker ps -q -a -f name=$_recognized_container)"
@@ -118,6 +146,6 @@ while [ $_waiting_flag -eq 0 ]; do
     fi
 done
 
-echo "> http://localhost:8080"
+echo "> http://localhost:$OPEN_WEBUI_PORT"
 
 _completed
