Informational echoes

diff --git a/.archived/backup-repos b/.archived/backup-repos
--- a/.archived/backup-repos
+++ b/.archived/backup-repos
@@ -31,8 +31,8 @@ _download_all_repos() {
 _select_repo() {
     cd "$REPOS_HOME"
 
-    echo ;
-    echo "Choose a repo to backup:"
+    echo >&2
+    echo "Choose a repo to backup:" >&2
     _repo_idx=1
     while IFS= read -r line || [ -n "$line" ]; do
         line=$( echo "${line//[$'\t\r\n']}" )
@@ -61,7 +61,7 @@ _select_repo() {
     done < $REPOS_LIST_FILE
 
     if [ "$_repo_flag" = "false" ]; then
-        echo "Invalid repo index"
+        echo "Invalid repo index" >&2
         _stopped
     fi
 }
@@ -70,9 +70,9 @@ _download_repo() {
     local _repo_zip=${1:-}
     local _repo_url=${2:-}
 
-    echo ;
-    echo "Output: $_repo_zip"
-    echo "URL: $_repo_url"
+    echo >&2
+    echo "Output: $_repo_zip" >&2
+    echo "URL: $_repo_url" >&2
     curl -L --create-dirs -o "${_repo_zip}.zip" "$_repo_url"
 }
 
diff --git a/.archived/sync-private b/.archived/sync-private
--- a/.archived/sync-private
+++ b/.archived/sync-private
@@ -29,16 +29,16 @@ done
 
 _sync_ops=( "Pull" "Push" )
 
-echo "Select an operation:"
+echo "Select an operation:" >&2
 for _idx in "${!_sync_ops[@]}"; do
     _op="${_sync_ops[$_idx]}"
 
-    echo "$((_idx+1))) $_op"
+    echo "$((_idx+1))) $_op" >&2
 done
 read -p "operation-index> " _op_index
 
 if [ -z "$_op_index" ]; then
-    echo "Invalid operation index"
+    echo "Invalid operation index" >&2
     _stopped
 fi
 
@@ -49,10 +49,10 @@ if [ "$_sync_op" = "Push" ]; then
 fi
 
 if [ $_push_flag -eq 1 ]; then
-    echo "Pushing changes to '$SYNC_FOLDER_PRIVATE_DIR'"
+    echo "Pushing changes to '$SYNC_FOLDER_PRIVATE_DIR'" >&2
     rsync -av "$ORG_ROAM_PRIVATE_DIR"/*.org "$SYNC_FOLDER_PRIVATE_DIR"
 else
-    echo "Pulling changes from '$SYNC_FOLDER_PRIVATE_DIR'"
+    echo "Pulling changes from '$SYNC_FOLDER_PRIVATE_DIR'" >&2
     rsync -av "$SYNC_FOLDER_PRIVATE_DIR"/*.org "$ORG_ROAM_PRIVATE_DIR"
 fi
 
diff --git a/games/launch-console b/games/launch-console
--- a/games/launch-console
+++ b/games/launch-console
@@ -154,15 +154,15 @@ _launch_celeste64() {
     bash ../sys/save-snapshot "$CELESTE_64_BACKUP_HOME"
 }
 
-echo "Select a console:"
-echo "1) Zelda 64: Recompiled"
-echo "2) 1964 GEPD Edition"
-echo "3) GameCube/Wii [Dolphin]"
-echo "4) Nintendo 64 [Mupen64Plus]"
-echo "5) GBA/GBC/GB [mGBA]"
-echo "6) 3DS [Azahar]"
-echo "7) SNES [Snes9x]"
-echo "8) Celeste 64: Fragments of the Mountain"
+echo "Select a console:" >&2
+echo "1) Zelda 64: Recompiled" >&2
+echo "2) 1964 GEPD Edition" >&2
+echo "3) GameCube/Wii [Dolphin]" >&2
+echo "4) Nintendo 64 [Mupen64Plus]" >&2
+echo "5) GBA/GBC/GB [mGBA]" >&2
+echo "6) 3DS [Azahar]" >&2
+echo "7) SNES [Snes9x]" >&2
+echo "8) Celeste 64: Fragments of the Mountain" >&2
 read -p "console-index> " _console_index
 
 case "$_console_index" in
@@ -191,7 +191,7 @@ case "$_console_index" in
         _launch_celeste64 "$@"
         ;;
     *)
-        echo "Invalid console index"
+        echo "Invalid console index" >&2
         _stopped
         ;;
 esac
diff --git a/gcloud/.libs/select-project b/gcloud/.libs/select-project
--- a/gcloud/.libs/select-project
+++ b/gcloud/.libs/select-project
@@ -9,8 +9,8 @@
 # Usage in script:
 #   . ./.libs/select-project  # Relative source
 
-echo ;
-echo "Select a project:"
+echo >&2
+echo "Select a project:" >&2
 
 for _idx in "${!GCLOUD_PROJECT_IDS[@]}"; do
     _project="${GCLOUD_PROJECT_IDS[$_idx]}"
@@ -38,7 +38,7 @@ if [ -n "$_project_index" ]; then
 fi
 
 if [ -z "$_project_selected" ]; then
-    echo "Invalid project index"
+    echo "Invalid project index" >&2
     exit 1
 else
     _project_id_selected=$( cut -d : -f 2 <<< "$_project_selected" )
diff --git a/gcloud/stop-emu b/gcloud/stop-emu
--- a/gcloud/stop-emu
+++ b/gcloud/stop-emu
@@ -37,18 +37,20 @@ _kill_pids() {
                 sleep 1
                 let "waited+=1"
                 if [ $waited -eq 120 ]; then
-                    echo -e "\nWaited two minutes, $pid is not responding to stop requests." >&2
+                    echo >&2
+                    echo "Waited two minutes, $pid is not responding to stop requests." >&2
                     exit 1
                 fi
             done
-            echo -e "\nStopped '$_name' running with PID $pid" >&2
+            echo >&2
+            echo "Stopped '$_name' running with PID $pid" >&2
         done
     else
         echo "Service '$_name' is not running" >&2
     fi
 }
 
-echo "Select a gcloud emulator:"
+echo "Select a gcloud emulator:" >&2
 for _idx in "${!GCLOUD_EMULATORS[@]}"; do
     _service="${GCLOUD_EMULATORS[$_idx]}"
     _name=$( cut -d : -f 2 <<< "$_service" )
@@ -63,7 +65,7 @@ read -p "emu-index> " _emu_index
 _emu_selected="${GCLOUD_EMULATORS[$((_emu_index-1))]}"
 
 if [ -z "$_emu_selected" ]; then
-    echo "Invalid emulator index"
+    echo "Invalid emulator index" >&2
     _stopped
 fi
 
diff --git a/props b/props
--- a/props
+++ b/props
@@ -23,7 +23,7 @@ done
 _prop_name=${1:-}
 
 if [ -n "$_prop_name" ]; then
-    _prop_value=$( eval "echo \$$_prop_name" )
+    _prop_value=$( eval "echo \$$_prop_name >&2" )
     echo "$_prop_value"
     exit 0
 fi
@@ -36,36 +36,36 @@ for _idx in "${!_all_props[@]}"; do
     _prop_value=$( eval "echo \$$_prop_name" )
 
     if [ -z "$_prop_value" ]; then
-        echo "$((_idx+1))) $_prop_name <empty>"
+        echo "$((_idx+1))) $_prop_name <empty>" >&2
     else
-        echo "$((_idx+1))) $_prop_name"
+        echo "$((_idx+1))) $_prop_name" >&2
     fi
 done
 read -p "env-index> " _prop_index
 
 if [ -z "$_prop_index" ]; then
-    echo "Invalid environment variable index"
+    echo "Invalid environment variable index" >&2
     _stopped
 fi
 
 _prop_name="${_all_props[$((_prop_index-1))]}"
 
 if [ -z "$_prop_name" ]; then
-    echo "Invalid environment variable index"
+    echo "Invalid environment variable index" >&2
     _stopped
 fi
 
-echo ;
+echo >&2
 
 _prop_value=$( eval "echo \$$_prop_name" )
 
 if [ -z "$_prop_value" ]; then
-    echo "$_prop_name=<empty>"
+    echo "$_prop_name=<empty>" >&2
 else
-    echo "$_prop_name=$_prop_value"
+    echo "$_prop_name=$_prop_value" >&2
 fi
 
 echo -n "$_prop_value" | xclip -sel clip
-echo Copied!!
+echo Copied!! >&2
 
 _completed
