Informational echo

diff --git a/gcloud/pubsub-topics b/gcloud/pubsub-topics
--- a/gcloud/pubsub-topics
+++ b/gcloud/pubsub-topics
@@ -62,10 +62,10 @@ _create_topics() {
             _topic="${TOPIC_DEFINITION_NAME[$_idx]}"
             _dead_letter="$_topic-DEAD_LETTER"
 
-            echo "Creating topic [$_topic] for project [$_project]"
+            echo "Creating topic [$_topic] for project [$_project]" >&2
             python publisher.py "$_project" create "$_topic"
 
-            echo "Creating dead-letter [$_dead_letter] for project [$_project]"
+            echo "Creating dead-letter [$_dead_letter] for project [$_project]" >&2
             python publisher.py "$_project" create "$_dead_letter"
 
             for _pull_idx in "${!TOPIC_DEFINITION_PULL_SUBS[@]}"; do
@@ -74,7 +74,7 @@ _create_topics() {
                 _pull_name=$( cut -d : -f 2 <<< "$_pull" )
 
                 if [ "$_topic_idx" = "$_idx" ]; then
-                    echo "Creating pull subscription [$_pull_name] for topic [$_project/$_topic]"
+                    echo "Creating pull subscription [$_pull_name] for topic [$_project/$_topic]" >&2
                     python subscriber.py "$_project" create-with-dead-letter-policy "$_topic" "$_pull_name" "$_dead_letter"
                 fi
             done
@@ -85,7 +85,7 @@ _create_topics() {
                 _push_name=$( cut -d : -f 2 <<< "$_push" )
 
                 if [ "$_topic_idx" = "$_idx" ]; then
-                    echo "Creating push subscription [$_push_name] for topic [$_project/$_topic]"
+                    echo "Creating push subscription [$_push_name] for topic [$_project/$_topic]" >&2
                     python subscriber.py "$_project" create-push "$_topic" "$_push_name" $PUBSUB_PUSH_ENDPOINT
                 fi
             done
@@ -98,24 +98,24 @@ _send_message() {
     # the fork file can be found in https://github.com/gfarfanb/dev-training/blob/main/Python/GCP/PubSub/publisher.py
 
     if [ -z "$_message_to_send" ]; then
-        echo "Defines a message with option: $0 -m <message>"
+        echo "Defines a message with option: $0 -m <message>" >&2
         _stopped
     fi
 
-    echo "Select a topic:"
+    echo "Select a topic:" >&2
     for _idx in "${!TOPIC_DEFINITION_NAME[@]}"; do
         _project="${TOPIC_DEFINITION_PROJECT[$_idx]}"
 
         if [ "$_project" = "$PUBSUB_PROJECT_ID" ]; then
             _topic="${TOPIC_DEFINITION_NAME[$_idx]}"
 
-            echo "$((_idx+1))) $_topic"
+            echo "$((_idx+1))) $_topic" >&2
         fi
     done
     read -p "topic-index> " _topic_index
 
     if [ -z "$_topic_index" ]; then
-        echo "Invalid topic index"
+        echo "Invalid topic index" >&2
         _stopped
     fi
 
@@ -142,16 +142,16 @@ _monitor_messages() {
         fi
     done
 
-    echo "Select a pull subscription:"
+    echo "Select a pull subscription:" >&2
     for _idx in "${!_pull_subs[@]}"; do
         _pull="${_pull_subs[$_idx]}"
 
-        echo "$((_idx+1))) $_pull"
+        echo "$((_idx+1))) $_pull" >&2
     done
     read -p "pull-subscription-index> " _pull_index
 
     if [ -z "$_pull_index" ]; then
-        echo "Invalid pull subscription index"
+        echo "Invalid pull subscription index" >&2
         _stopped
     fi
 
diff --git a/misc/download-audio b/misc/download-audio
--- a/misc/download-audio
+++ b/misc/download-audio
@@ -49,18 +49,18 @@ _pack_audios() {
         local _package="audio${_counter}.zip"
 
         zip -r $_package . -i *.mp3
-        echo "ZIP generated '$_package' in: $YT_DLP_AUDIO_OUTPUT_FOLDER"
+        echo "ZIP generated '$_package' in: $YT_DLP_AUDIO_OUTPUT_FOLDER" >&2
 
         read -p "Remove packed MP3 files? y/n> " _yesno
         case $_yesno in
             [Yy]*)
                 find . -name '*.mp3' -type f -delete
                 find . -type d -empty -delete
-                echo "MP3 files were cleaned"
+                echo "MP3 files were cleaned" >&2
             ;;
         esac
     else
-        echo "MP3 files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER"
+        echo "MP3 files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER" >&2
     fi
 
     _completed
@@ -71,9 +71,9 @@ _move_outputs() {
 
     if [ -n "$(find . -name '*.zip')" ]; then
         rsync -av --remove-source-files $YT_DLP_AUDIO_OUTPUT_FOLDER/*.zip "$DOWNLOADS_HOME"
-        echo "ZIP files moved to: $DOWNLOADS_HOME"
+        echo "ZIP files moved to: $DOWNLOADS_HOME" >&2
     else
-        echo "ZIP files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER"
+        echo "ZIP files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER" >&2
     fi
 
     _completed
@@ -148,8 +148,8 @@ _download_resource() {
             _download_audio "$line" $_quality
         done < $_list
 
-        echo ;
-        cat $_list
+        echo >&2
+        cat $_list >&2
         rm -f $_list
     fi
 }
@@ -185,10 +185,10 @@ while getopts "u:i:l:pmh" opt; do
     esac
 done
 
-echo ;
-echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:"
-echo "  quote: $0 -u '...&<param>=<value>'"
-echo "  escape: $0 -u ...\\&<param>=<value>"
+echo >&2
+echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:" >&2
+echo "  quote: $0 -u '...&<param>=<value>'" >&2
+echo "  escape: $0 -u ...\\&<param>=<value>" >&2
 
 if [ $_quality -eq -1 ]; then
     _quality=$( _select_quality )
diff --git a/misc/download-video b/misc/download-video
--- a/misc/download-video
+++ b/misc/download-video
@@ -52,18 +52,18 @@ _pack_videos() {
         local _package="video${_counter}.zip"
 
         zip -r $_package . -i *.mp4
-        echo "ZIP generated '$_package' in: $YT_DLP_VIDEO_OUTPUT_FOLDER"
+        echo "ZIP generated '$_package' in: $YT_DLP_VIDEO_OUTPUT_FOLDER" >&2
 
         read -p "Remove packed MP4 files? y/n> " _yesno
         case $_yesno in
             [Yy]*)
                 find . -name '*.mp4' -type f -delete
                 find . -type d -empty -delete
-                echo "MP4 files were cleaned"
+                echo "MP4 files were cleaned" >&2
             ;;
         esac
     else
-        echo "MP4 files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER"
+        echo "MP4 files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER" >&2
     fi
 
     _completed
@@ -74,9 +74,9 @@ _move_outputs() {
 
     if [ -n "$(find . -name '*.zip')" ]; then
         rsync -av --remove-source-files $YT_DLP_VIDEO_OUTPUT_FOLDER/*.zip "$DOWNLOADS_HOME"
-        echo "ZIP files moved to: $DOWNLOADS_HOME"
+        echo "ZIP files moved to: $DOWNLOADS_HOME" >&2
     else
-        echo "ZIP files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER"
+        echo "ZIP files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER" >&2
     fi
 
     _completed
@@ -222,8 +222,8 @@ _download_resource() {
             _download_video "$line" "$_res" "$_cookies"
         done < $_list
 
-        echo ;
-        cat $_list
+        echo >&2
+        cat $_list >&2
         rm -f $_list
     fi
 
@@ -276,10 +276,10 @@ if [ $_available_flag -eq 1 ]; then
     _completed
 fi
 
-echo ;
-echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:"
-echo "  quote: $0 -u '...&<param>=<value>'"
-echo "  escape: $0 -u ...\\&<param>=<value>"
+echo >&2
+echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:" >&2
+echo "  quote: $0 -u '...&<param>=<value>'" >&2
+echo "  escape: $0 -u ...\\&<param>=<value>" >&2
 
 _download_resource "$_src_url" "$_list_file" "$_resolution" "$_cookies_file"
 
diff --git a/misc/mp4-to-mp3 b/misc/mp4-to-mp3
--- a/misc/mp4-to-mp3
+++ b/misc/mp4-to-mp3
@@ -26,8 +26,8 @@ _convert() {
 
     ffmpeg -y -loglevel warning -i "$_mp4" -vn -acodec libmp3lame -ac 2 -ab 160k -ar 48000 "$_output"
 
-    echo "Input: $_mp4"
-    echo "Output: $_output"
+    echo "Input: $_mp4" >&2
+    echo "Output: $_output" >&2
 }
 
 _mp4_location=""
@@ -48,8 +48,8 @@ while getopts "i:o:h" opt; do
 done
 
 if [ -d "$_mp4_location" ]; then
-    echo "Reading: $_mp4_location"
-    echo ;
+    echo "Reading: $_mp4_location" >&2
+    echo >&2
 
     for _mp4 in "$_mp4_location"/*.mp4 ; do
         _convert "$_mp4"
@@ -57,7 +57,7 @@ if [ -d "$_mp4_location" ]; then
 elif [ -f "$_mp4_location" ]; then
     _convert "$_mp4_location"
 else
-    echo "Invalid MP4 location/file: $_mp4_location"
+    echo "Invalid MP4 location/file: $_mp4_location" >&2
     _stopped
 fi
 
diff --git a/misc/transcribe b/misc/transcribe
--- a/misc/transcribe
+++ b/misc/transcribe
@@ -59,7 +59,7 @@ done
 if [ -f "$_resource" ]; then
     _transcribe "$_resource" "$_output"
 else
-    echo "Invalid resource: $_resource"
+    echo "Invalid resource: $_resource" >&2
     _stopped
 fi
 
diff --git a/sync-cloud b/sync-cloud
--- a/sync-cloud
+++ b/sync-cloud
@@ -47,16 +47,16 @@ done
 _sync_ops=( "Pull" "Push" )
 
 if [ -z "$_sync_op" ]; then
-    echo "Select an operation:"
+    echo "Select an operation:" >&2
     for _idx in "${!_sync_ops[@]}"; do
         _op="${_sync_ops[$_idx]}"
 
-        echo "$((_idx+1))) $_op"
+        echo "$((_idx+1))) $_op" >&2
     done
     read -p "operation-index> " _op_index
 
     if [ -z "$_op_index" ]; then
-        echo "Invalid operation index"
+        echo "Invalid operation index" >&2
         _stopped
     fi
 
@@ -73,14 +73,14 @@ for _src in "${CLOUD_REMOTE_SOURCES[@]}"; do
     _path=$( _trim_separator "$_path" )
 
     if [ $_push_flag -eq 1 ]; then
-        echo "Pushing changes to '$_config:$_path'"
+        echo "Pushing changes to '$_config:$_path'" >&2
         rclone copy "$_options" "$_cloud_home/$_config/$_path" $_config:$_path
 
         if [ $_sync_flag -eq 1 ]; then
             rclone sync "$_options" "$_cloud_home/$_config/$_path" $_config:$_path
         fi
     else
-        echo "Pulling changes from '$_config:$_path'"
+        echo "Pulling changes from '$_config:$_path'" >&2
         rclone copy "$_options" $_config:$_path "$_cloud_home/$_config/$_path"
 
         if [ $_sync_flag -eq 1 ]; then
